[manager]
layout = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { exec = '$EDITOR "$@"', block = true, for = "unix" },
  { exec = 'code "%*"', orphan = true, for = "windows" },
]
browse = [{ exec = 'firefox "$@"', block = false, for = "linux" }]
open = [
  { exec = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { exec = 'open "$@"', desc = "Open", for = "macos" },
  { exec = 'start "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { exec = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { exec = 'explorer /select,%1', orphan = true, desc = "Reveal", for = "windows" },
  { exec = 'qeegie %1', block = false, for = "linux" },
  # { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { exec = 'unar "$1"', desc = "Extract here", for = "unix" },
  { exec = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
  { exec = 'mpv "$@"', orphan = true, for = "unix" },
  { exec = 'mpv "%1"', orphan = true, for = "windows" },
  { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

[open]
rules = [
  { name = "*/", use = [
    "edit",
    "open",
    "reveal",
  ] },

  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  { name = "*.md", use = "text" },
  { name = "*.org", use = "text" },
  { name = "*.html", use = [
    "browse",
    "text",
  ] },
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  { mime = "video/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "audio/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "inode/x-empty", use = [
    "edit",
    "reveal",
  ] },

  { mime = "application/json", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },

  { mime = "application/zip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/gzip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-tar", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-bzip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-bzip2", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-7z-compressed", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-rar", use = [
    "extract",
    "reveal",
  ] },

  { mime = "*", use = [
    "open",
    "reveal",
  ] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[plugins]
preload = []

[log]
enabled = false

# [manager]
# layout = [1, 4, 3]
# sort_by = "natural"
# sort_sensitive = false
# sort_reverse = false
# sort_dir_first = true
# show_hidden = true
# show_symlink = true
#
# [preview]
# tab_size = 2
# max_width = 600
# max_height = 900
# cache_dir = ""
#
# [opener]
# folder = [
#   { exec = 'open -R "$@"', display_name = "Reveal in Finder" },
#   { exec = '$EDITOR "$@"' },
# ]
# archive = [{ exec = 'unar "$1"', display_name = "Extract here" }]
# text = [{ exec = '$EDITOR "$@"', block = true }]
# image = [
#   { exec = 'open "$@"', display_name = "Open" },
#   { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show EXIF" },
# ]
# video = [
#   { exec = 'mpv "$@"' },
#   { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
# ]
# audio = [
#   { exec = 'mpv "$@"' },
#   { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
# ]
# fallback = [
#   { exec = 'open "$@"', display_name = "Open" },
#   { exec = 'open -R "$@"', display_name = "Reveal in Finder" },
# ]
#
# [open]
# rules = [
#   { name = "*/", use = "folder" },
#   { name = "*.md", use = "text" },
#   { mime = "text/*", use = "text" },
#   { mime = "image/*", use = "image" },
#   { mime = "video/*", use = "video" },
#   { mime = "audio/*", use = "audio" },
#   { mime = "inode/x-empty", use = "text" },
#
#   { mime = "application/json", use = "text" },
#   { mime = "*/javascript", use = "text" },
#
#   { mime = "application/zip", use = "archive" },
#   { mime = "application/gzip", use = "archive" },
#   { mime = "application/x-tar", use = "archive" },
#   { mime = "application/x-bzip", use = "archive" },
#   { mime = "application/x-bzip2", use = "archive" },
#   { mime = "application/x-7z-compressed", use = "archive" },
#   { mime = "application/x-rar", use = "archive" },
#
#   { mime = "*", use = "fallback" },
# ]
#
# [tasks]
# micro_workers = 5
# macro_workers = 10
# bizarre_retry = 5
#
# [log]
# enabled = false
